spring.application.name=SG

# Tic-tac-toe default settings
game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

# Taquin default settings
game.taquin.default-player-count=1
game.taquin.default-board-size=4

# Connect Four default settings
game.connectfour.default-player-count=2
game.connectfour.default-board-size=7

# Do not use the server OS language as fallback:
spring.messages.fallback-to-system-locale=false

# JDBC
spring.datasource.url=jdbc:postgresql://localhost:5432/square_games
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
# To execute database creation at startup (if not exist)
spring.sql.init.mode=always

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

