spring.application.name=SG

# Active Spring Profile (postgres or h2)
spring.profiles.active=postgres

# Tic-tac-toe default settings
game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

# Taquin default settings
game.taquin.default-player-count=1
game.taquin.default-board-size=4

# Connect Four default settings
game.connectfour.default-player-count=2
game.connectfour.default-board-size=7

# Do not use the server OS language as fallback:
spring.messages.fallback-to-system-locale=false

# In order to communicate with Square Users
users.service.url=http://localhost:8081

# JWT Public Key Path
jwt.public-key-path=classpath:certs/public_key.pem
